# Generated by Django 4.1.7 on 2023-03-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='address_tour',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='amount_people_tour',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date_begin_tour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='status_tour',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
