# Generated by Django 4.1.7 on 2023-03-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0003_alter_ratingvote_amount_star_voting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='code_bill',
            field=models.CharField(db_index=True, max_length=25, null=True, unique=True),
        ),
    ]
