# Generated by Django 4.1.7 on 2023-03-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0004_alter_bill_code_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_tour',
            field=models.ImageField(null=True, upload_to='traveling/static/traveling/tour/%Y/%m'),
        ),
    ]
