# Generated by Django 4.1.7 on 2023-03-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0007_alter_tour_image_tour_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='totals_minus_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
