# Generated by Django 4.1.7 on 2023-03-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0008_ticket_totals_minus_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
