# Generated by Django 4.1.7 on 2023-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0009_ticket_price_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='amount_ticket',
            field=models.SmallIntegerField(default=1),
        ),
    ]
