# Generated by Django 4.1.7 on 2023-03-22 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0010_ticket_amount_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='traveling.bill'),
        ),
    ]
