# Generated by Django 4.1.7 on 2023-03-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0011_alter_ticket_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='image_tour',
            field=models.ImageField(null=True, upload_to='traveling/static/travel/tour/%Y/%m'),
        ),
    ]
