# Generated by Django 4.1.7 on 2023-04-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0017_alter_tour_image_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='amount_like',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tour',
            name='amount_people_tour',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='amount_popular_tour',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
