# Generated by Django 4.2 on 2023-04-10 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0020_tourimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='method_pay',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
