# Generated by Django 4.2 on 2023-04-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0022_tour_country_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='rating_count_tour',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10, null=True),
        ),
    ]
