# Generated by Django 4.2 on 2023-04-29 09:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0023_tour_rating_count_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('kw_blog', models.CharField(db_index=True, max_length=25)),
                ('title_blog', models.CharField(max_length=255)),
                ('content_blog', ckeditor.fields.RichTextField()),
                ('image_blog', models.ImageField(null=True, upload_to='blog/%Y/%m')),
                ('image_content1_blog', models.ImageField(null=True, upload_to='blog/%Y/%m')),
                ('image_content2_blog', models.ImageField(null=True, upload_to='blog/%Y/%m')),
                ('address_blog', models.CharField(max_length=255, null=True)),
                ('country_blog', models.CharField(max_length=255, null=True)),
                ('count_like_blog', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content_cmt', ckeditor.fields.RichTextField()),
                ('amount_like_cmt', models.IntegerField(null=True)),
                ('status_cmt', models.CharField(max_length=25)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traveling.blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
